version: '2'
services:
    #ror:
    #    build: ror/.
    #    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 80 -b '0.0.0.0'" 
    #    volumes:
    #        - ./ror/:/ror
        #ports:
        #    - "3000:3000"
    #    restart: always
    #    networks:
    #        - nginx_default
    node:
        privileged: true
        build: node/.
        command: node server.js
     #   depends_on:
     #       - ror
           # - redis
        ports:
            - "8080:8080"
    #    restart: always
        devices:
        - /dev/snd
        volumes:
        - ./node/:/node
        - /node/node_modules
        restart: always
    #    networks:
    #        - nginx_default
    http:
        build: http/.
        command: http-server . -p 80
        #depends_on: 
        #    - ror
        ports:
            - "8088:80"
        volumes:
            - ./http/:/http
            - /http/node_modules
        restart: always
    lb:
        build: lb/.
        command: node .
        ports:
            - "3000:3000"
        volumes:
            - ./lb/:/lb
            - /lb/node_modules
        restart: always
    #    networks:
    #        - nginx_default
    #redis:
    #    build: redis/.
    #    command: redis-server /usr/local/etc/redis/redis.conf
    #    #image: redis
    #    #ports:
        #    - "6379:6379"
    #    volumes:
    #        - /redis/redis.conf:/usr/local/etc/redis/redis.conf
    #    restart: always
    #    networks:
    #        - nginx_default
#networks:
#    nginx_default:
#        external: true
